var fonts = ["Aaargh",
"ABeeZee",
// "Action Man",
// "Action Man Extended",
// "Action Man Shaded",
// "Adobe Arabic",
"Adobe Caslon Pro",
// "Adobe Devanagari",
// "Adobe Fan Heiti Std",
// "Adobe Fangsong Std",
"Adobe Garamond Pro",
"Adobe Gothic Std",
// "Adobe Gurmukhi",
// "Adobe Hebrew",
// "Adobe Heiti Std",
// "Adobe Kaiti Std",
// "Adobe Ming Std",
// "Adobe Myungjo Std",
// "Adobe Naskh",
// "Adobe Song Std",
"Afta sans",
"Afta serif",
"Alegreya",
"Alegreya Sans",
// "Alegreya Sans SC",
// "Alegreya SC",
"Aller",
// "Aller Display",
"Aller Light",
"Amaranth",
"Amble",
"American Typewriter",
"Andada",
// "Andada SC",
"Andale Mono",
"Andika Basic",
// "Anonymous Pro",
"Apple Braille",
// "Apple Chancery",
"Apple SD Gothic Neo",
// "Apple Symbols",
// "Apple 彩色表情符號",
"AppleGothic",
"AppleMyungjo",
"Architects Daughter",
"Archivo Black",
"Archivo Narrow",
"Arial",
"Arial Black",
"Arial Hebrew",
"Arial Hebrew Scholar",
"Arial Narrow",
"Arial Rounded MT Bold",
"Arial Unicode MS",
"Arimo",
"Armata",
"Arsenal",
"Asap",
"Athelas",
"Aurulent Sans",
"Aurulent Sans Mono",
"Avenir",
"Avenir Next",
"Avenir Next Condensed",
// "Ayuthaya",
"Bangla MN",
"Bangla Sangam MN",
// "Baoli SC",
"Baskerville",
"Big Caslon",
// "Birch Std",
"Bitstream Vera Sans",
"Bitstream Vera Sans Mono",
"Bitstream Vera Serif",
"Bitter",
// "Blackoak Std",
"Bodoni 72",
"Bodoni 72 Oldstyle",
// "Bodoni 72 Smallcaps",
// "Bodoni Ornaments",
"BPmono",
"BPreplay",
"Bradley Hand",
"Brandon Grotesque",
"Bree Serif",
// "Brush Script MT",
// "Brush Script Std",
"Cabin",
"Cantarell",
"Cardo",
"Carrois Gothic",
// "Carrois Gothic SC",
"Caviar Dreams",
"Chalkboard",
"Chalkboard SE",
"Chalkduster",
"Chaparral Pro",
// "Charlemagne Std",
"Charter",
"Clear Sans",
"Clear Sans Light",
"Clear Sans Medium",
"Clear Sans Thin",
"CMU Serif",
"Cochin",
// "College",
"Comic Neue",
"Comic Neue Angular",
"Comic Sans MS",
"Cooper Hewitt",
"Cooper Std",
// "Copperplate",
"Copse",
"Corsiva Hebrew",
"Courier",
"Courier New",
"DejaVu Sans",
"DejaVu Sans Mono",
"Devanagari MT",
"Devanagari Sangam MN",
"Didot",
"DIN Alternate",
"DIN Condensed",
"Droid Sans",
"Euphemia UCAS",
"Existence",
"Exo",
"Fira Sans",
"Futura",
"Geneva",
"Georgia",
// "Giddyup Std",
"Gill Sans",
"Gujarati MT",
"Gujarati Sangam MN",
"GungSeo",
"Gurmukhi MN",
"Gurmukhi MT",
"Gurmukhi Sangam MN",
// "Hannotate SC",
"Hannotate TC",
// "HanziPen SC",
"HanziPen TC",
"HeadLineA",
// "Heiti SC",
"Heiti TC",
"Helvetica",
"Helvetica Neue",
// "Herculanum",
"Hiragino Kaku Gothic Pro",
"Hiragino Kaku Gothic ProN",
"Hiragino Kaku Gothic Std",
"Hiragino Kaku Gothic StdN",
"Hiragino Maru Gothic Pro",
"Hiragino Maru Gothic ProN",
"Hiragino Mincho Pro",
"Hiragino Mincho ProN",
"Hiragino Sans GB",
"Hobo Std",
"Hoefler Text",
"Impact",
"InaiMathi",
"Iowan Old Style",
"ITF Devanagari",
"Josefin Sans",
"Kailasa",
// "Kaiti SC",
"Kaiti TC",
"Kannada MN",
"Kannada Sangam MN",
"Kefa",
"Khmer MN",
"Khmer Sangam MN",
"Kohinoor Devanagari",
// "Kokonor",
"Kozuka Gothic Pr6N",
"Kozuka Gothic Pro",
"Kozuka Mincho Pr6N",
"Kozuka Mincho Pro",
"Krungthep",
// "Lantinghei SC",
"Lantinghei TC",
"Lao MN",
"Lao Sangam MN",
// "LastResort",
"Lato",
"Letter Gothic Std",
// "Libian SC",
"LiHei Pro",
"LiSong Pro",
// "Lithos Pro",
"Lobster 1.3",
"Lucida Grande",
"Luminari",
"Malayalam MN",
"Malayalam Sangam MN",
"Marion",
"Marker Felt",
"Menlo",
// "Mesquite Std",
"Microsoft Sans Serif",
"Minion Pro",
"Monaco",
"Mshtakan",
"Myanmar MN",
"Myanmar Sangam MN",
"Myriad Arabic",
"Myriad Hebrew",
"Myriad Pro",
// "Nanum Brush Script",
"Nanum Gothic",
"Nanum Myeongjo",
// "Nanum Pen Script",
"New Peninim MT",
"Noteworthy",
"Nueva Std",
"OCR A Std",
"Open Sans",
"Optima",
// "Orator Std",
"Oriya MN",
"Oriya Sangam MN",
"Osaka",
"Palatino",
"Papyrus",
// "PCMyungjo",
// "Phosphate",
// "PilGi",
"Plantagenet Cherokee",
// "Poplar Std",
"Prestige Elite Std",
"PT Mono",
"PT Sans",
"PT Sans Caption",
"PT Sans Narrow",
"PT Serif",
"PT Serif Caption",
"Quicksand",
"Raanana",
"Roboto",
"Roboto Condensed",
// "Rosewood Std",
"Sathu",
// "Savoye LET",
"Segoe UI",
"Seravek",
"Shree Devanagari 714",
// "SignPainter",
"Silom",
"Sinhala MN",
"Sinhala Sangam MN",
"Skia",
"Skyhook Mono",
// "Snell Roundhand",
// "Songti SC",
"Songti TC",
"Source Code Pro",
"Source Sans Pro",
"Source Serif Pro",
"Stencil Std",
"STFangsong",
"STHeiti",
"STIXGeneral",
// "STIXIntegralsD",
// "STIXIntegralsSm",
// "STIXIntegralsUp",
// "STIXIntegralsUpD",
// "STIXIntegralsUpSm",
// "STIXNonUnicode",
// "STIXSizeFiveSym",
// "STIXSizeFourSym",
// "STIXSizeOneSym",
// "STIXSizeThreeSym",
// "STIXSizeTwoSym",
// "STIXVariants",
"STKaiti",
"STSong",
"Sukhumvit Set",
"Superclarendon",
"Symbol",
"System Font",
"Tahoma",
"Tamil MN",
"Tamil Sangam MN",
"Tekton Pro",
"Telugu MN",
"Telugu Sangam MN",
"Thonburi",
"Times",
"Times New Roman",
// "Trajan Pro",
"Trajan Pro 3",
// "Trattatello",
"Trebuchet MS",
"Ubuntu",
"Ubuntu Condensed",
"Ubuntu Mono",
"Ubuntu Titling",
"Verdana",
// "Wawati SC",
"Wawati TC",
// "Webdings",
// "Weibei SC",
"Weibei TC",
// "Xingkai SC",
// "xkcd",
// "Yuanti SC",
"YuGothic",
"YuMincho",
// "Yuppy SC",
"Yuppy TC",
// "Zapfino"
];


var boldfonts = [
"Archivo Black",
"Aller Display",
"Adobe Gothic Std",
"Arial Black",
"Arial Rounded MT Bold",
"Cooper Std",
"HeadLineA",
"Hiragino Kaku Gothic Std",
"Hiragino Kaku Gothic StdN",
"Impact",
"Hobo Std",
"Krungthep",
"Marker Felt",
"Silom",
"Superclarendon",
"BPreplay",
"Source Code Pro"
]

